### ISSUE TITLE
Invalid documentation url

### ISSUE THREAD

**Issue by philpott** [Jude-Nwachukwu/IP-Transformer-Anonymizer#1]
https://github.com/Jude-Nwachukwu/IP-Transformer-Anonymizer/blob/87a524b8f688c33ab165d4f9c4f03c68305385dd/metadata.yaml#L3C35-L3C48

The documentation URL is invalid (invalid github username/org)

**Comment by Jude-Nwachukwu** [comment]
Thanks for catching that; much appreciated.

Fixed the issue: added the documentation URL
